# Generated by Django 5.1.6 on 2025-05-11 17:18

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WeatherData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city", models.CharField(max_length=100)),
                ("temperature_c", models.FloatField()),
                ("condition_text", models.CharField(max_length=100)),
                ("wind_kph", models.FloatField()),
                ("humidity", models.IntegerField()),
                ("last_updated", models.DateTimeField()),
            ],
        ),
    ]
