# Generated by Django 5.1.6 on 2025-05-11 17:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("weather", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="weatherdata",
            name="cloud",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="weatherdata",
            name="condition_icon",
            field=models.URLField(default=""),
        ),
        migrations.AddField(
            model_name="weatherdata",
            name="country",
            field=models.CharField(default="Unknown", max_length=100),
        ),
        migrations.AddField(
            model_name="weatherdata",
            name="feelslike_c",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="weatherdata",
            name="gust_kph",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="weatherdata",
            name="local_time",
            field=models.CharField(default="Unknown", max_length=100),
        ),
        migrations.AddField(
            model_name="weatherdata",
            name="precip_mm",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="weatherdata",
            name="pressure_mb",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="weatherdata",
            name="region",
            field=models.CharField(default="Unknown", max_length=100),
        ),
        migrations.AddField(
            model_name="weatherdata",
            name="uv",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="weatherdata",
            name="vis_km",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="weatherdata",
            name="wind_dir",
            field=models.CharField(default="Unknown", max_length=10),
        ),
        migrations.AlterField(
            model_name="weatherdata",
            name="condition_text",
            field=models.CharField(default="Unknown", max_length=100),
        ),
        migrations.AlterField(
            model_name="weatherdata",
            name="humidity",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="weatherdata",
            name="last_updated",
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="weatherdata",
            name="temperature_c",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="weatherdata",
            name="wind_kph",
            field=models.FloatField(default=0.0),
        ),
    ]
