# Generated by Django 5.1.6 on 2025-05-11 19:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("weather", "0002_weatherdata_cloud_weatherdata_condition_icon_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="weatherdata",
            name="condition_code",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="weatherdata",
            name="dewpoint_c",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="weatherdata",
            name="dewpoint_f",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="weatherdata",
            name="feelslike_f",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="weatherdata",
            name="gust_mph",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="weatherdata",
            name="heatindex_c",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="weatherdata",
            name="heatindex_f",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="weatherdata",
            name="is_day",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="weatherdata",
            name="precip_in",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="weatherdata",
            name="pressure_in",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="weatherdata",
            name="temp_f",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="weatherdata",
            name="vis_miles",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="weatherdata",
            name="wind_degree",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="weatherdata",
            name="wind_mph",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="weatherdata",
            name="windchill_c",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="weatherdata",
            name="windchill_f",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="weatherdata",
            name="city",
            field=models.CharField(default="Unknown", max_length=100),
        ),
    ]
