# Generated by Django 5.1.6 on 2025-05-12 10:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("weather", "0003_weatherdata_condition_code_weatherdata_dewpoint_c_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="weatherdata",
            name="air_quality_co",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="weatherdata",
            name="air_quality_gb_defra_index",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="weatherdata",
            name="air_quality_no2",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="weatherdata",
            name="air_quality_o3",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="weatherdata",
            name="air_quality_pm10",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="weatherdata",
            name="air_quality_pm2_5",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="weatherdata",
            name="air_quality_so2",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="weatherdata",
            name="air_quality_us_epa_index",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
